name: 'test'

on:
  push:
    branches:
      - main
  workflow_dispatch: # Run manually.

jobs:
  generate-matrix:
    name: 'test'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:
      - name: now
        uses: zchryr/actions-time-calculate/now@main

      - name: sleep
        run: |
          sleep 5

      - name: calculate
        uses: zchryr/actions-time-calculate/calculate@main

      - name: cat
        run: |
          cat *.json
