name: 'test'

on:
  push:
    branches:
      - main
  workflow_dispatch: # Run manually.

jobs:
  generate-matrix:
    name: 'test'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:
      - name: now
        uses: zchryr/actions-time-calculate/now@main

      - name: sleep
        run: |
          sleep 5

      - name: calculate
        uses: zchryr/actions-time-calculate/calculate@main
        with:
          TIME_NOW: ${{ steps.now.outputs.TIME_NOW }}

      - name: echo
        run: |
          echo "TIME_CALCULATED"
          echo "${{ steps.calc.outputs.TIME_CALCULATED }}"

      - name: Build Notification
        uses: zchryr/build-notifier-action@v1.0.11
        with:
          body: ${{ steps.calc.outputs.TIME_CALCULATED }}"
          url: ${{ secrets.TINES_WEBHOOK }}
          response_code: 201
          repo: ${{ github.repository }}
          workflow: $WORKFLOW
        env:
          WORKFLOW: ${{ github.workflow }}
