name: 'actions-time-calculate: calculate'
description: 'Used the previously saved epoch time and calculate the difference.'
author: 'Zachary R'

runs:
  using: 'node20'
  main: 'index.js'
  post: 'post.js'
